apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-app-config
  namespace: rag-system
data:
  QDRANT_URL: "http://qdrant:6333"
  QDRANT_COLLECTION: "k3s-docs"
  DOCS_PATH: "/home/sydney/Workstation/kubenetes/k3s"
  EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
  CHAT_MODEL: "llama-3.1-8b-instant"
  CHUNK_SIZE: "500"
  CHUNK_OVERLAP: "50"