apiVersion: v1
kind: Service
metadata:
  name: rag-app
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: rag-app
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
    name: http
